%%  cue / image, across tasks

cue_look_out = jja_get_social_image_looking_duration( ...
  'is_parallel', true ...
  , 'start_event', 'display_info_cues' ...
  , 'stop_event', 'display_social_image' ...
);

image_look_out = jja_get_social_image_looking_duration( ...
  'is_parallel', true ...
  , 'start_event', 'display_social_image' ...
  , 'stop_event', 'reward' ...
);

%%  juice and social combined cues

juice_out = jja_get_social_image_looking_duration( ...
  'start_event', 'display_info_cues', 'stop_event', 'reward' ...
);

soc_out = jja_get_social_image_looking_duration( ...
  'start_event', 'display_info_cues', 'stop_event', 'display_social_image' ...
);

%%  cue lookdur

jja_plot_cue_and_image_lookdur_final( cue_look_out, true ...
  , 'is_normalized', true ...
);

%%  image lookdur

jja_plot_cue_and_image_lookdur_final( image_look_out, false ...
  , 'is_normalized', true ...
);

%%  juice vs. social cues

jja_plot_lookdur_juice_social_cues( juice_out, soc_out );